version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app/
    network_mode: "host"
    environment:
      - OPENALEX_CONTACT_EMAIL
      - OPENAI_API_KEY
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
