version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app/
    environment:
      - OPENALEX_CONTACT_EMAIL
      - OPENAI_API_KEY
      - DB_HOST=db
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DEBUG
    depends_on:
      - db
  db:
    build: setup
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./setup/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
