version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app/
    environment:
      - OPENALEX_CONTACT_EMAIL
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
