from os import environ

import pyalex

pyalex.config.email = environ.get("OPENALEX_CONTACT_EMAIL")


class Work:
    def __init__(self, pyalex_work: pyalex.Work):
        self.title = pyalex_work['title']
        # First three authors for now
        self.authors = [author['author']['display_name'] for author in pyalex_work['authorships'][:3]]
        self.id = pyalex_work['ids']['openalex']
        # Depending on the query, OpenAlex may not return a relevance score
        self.oa_relevance_score = pyalex_work.get('relevance_score', None)
        # Pyalex overrides __getitem__ to reconstruct the abstract from the inverted index on the fly.
        # Calling pyalex_work.get would circumvent that custom logic and return None, even if an abstract is present.
        # For that reason, we need to check if abstract_inverted_index exists.
        self.abstract = pyalex_work['abstract'] if pyalex_work['abstract_inverted_index'] else None

        # Relevance score as calculated by this application
        self.relevance_score = None
        # Summary as generated by this application
        self.summary = None

    def __str__(self):
        return f"'{self.title}' by [{', '.join(self.authors)}] ({self.id})"


def search_works(query: str) -> [Work]:
    pyalex_works = (pyalex.Works()
                    .search(query)
                    .sort(relevance_score="desc")
                    .get())

    return [Work(pyalex_work) for pyalex_work in pyalex_works]
